# Generated by Django 4.0.3 on 2022-03-15 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inheritapp', '0005_alter_myexam_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myexam',
            options={'ordering': ['city']},
        ),
    ]
