# Generated by Django 4.0.3 on 2022-03-16 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inheritapp', '0006_alter_myexam_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('roll', models.IntegerField()),
            ],
        ),
    ]
