# Generated by Django 4.0.3 on 2022-03-16 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inheritapp', '0008_stu1_alter_stu_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='proxystudent',
            fields=[
            ],
            options={
                'ordering': ['name'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('inheritapp.stu1',),
        ),
        migrations.AlterModelManagers(
            name='stu1',
            managers=[
            ],
        ),
    ]
